
	package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.io;

import java.io.FilterOutputStream;
import java.io.IOException;
import java.io.OutputStream;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class FilterOutputStream_2_6_MockUse {

	public FilterOutputStream obj = null;
	public FilterOutputStream_2_6_MockUse(OutputStream p) {
		obj = new FilterOutputStream(p);
		callFilterOutputStreamMethods();
		callObjectMethods();
		callOutputStreamMethods();
	}

	public void callFilterOutputStreamMethods() {
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callOutputStreamMethods() {
	}
}