
package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.io;

import java.io.IOException;
import java.io.OutputStream;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class OutputStream_2_6_MockUse {

	public OutputStream obj = null;
	public OutputStream_2_6_MockUse() {
		obj = new OutputStream_Extension();
		callOutputStreamMethods();
		callObjectMethods();
	}

	public void callOutputStreamMethods() {
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}