package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.util;

import java.util.ArrayList;
import java.util.HashSet;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class HashSet_2_6_MockUse {

	public HashSet obj = null;
	public HashSet_2_6_MockUse() {
		obj = new HashSet();
		obj = new HashSet(
			2);
		obj = new HashSet(
			2, (float) 0.2);
		obj = new HashSet(
			new HashSet());
		callHashSetMethods();
		callObjectMethods();
		callAbstractCollectionMethods();
		callAbstractSetMethods();
	}

	public void callHashSetMethods() {
		obj.clone();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callAbstractCollectionMethods() {
		obj.toArray();
		obj.toArray(new Object[] {});
		obj.add(new Object());
		obj.addAll(new ArrayList());
		obj.contains(new Object());
		obj.containsAll(new ArrayList());
		obj.isEmpty();
		obj.remove(new Object());
		obj.removeAll(new ArrayList());
		obj.retainAll(new ArrayList());
		obj.size();
		obj.toString();
		obj.iterator();
		obj.clear();
	}
	public void callAbstractSetMethods() {
		obj.equals(new Object());
		obj.removeAll(new ArrayList());
		obj.hashCode();
	}
}
