package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.util;

import java.util.Random;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Random_2_6_MockUse {

	public Random obj = null;
	public Random_2_6_MockUse() {
		obj = new Random();
		obj = new Random(
			3L);
		callRandomMethods();
		callObjectMethods();
	}

	public void callRandomMethods() {
		obj.nextBoolean();
		obj.nextDouble();
		obj.nextGaussian();
		obj.nextFloat();
		obj.nextInt();
		obj.nextInt(2);
		obj.nextLong();
		obj.nextBytes(new byte[1]);
		obj.setSeed(3L);
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}