package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.logging;

import java.util.logging.Formatter;
import java.util.logging.Level;
import java.util.logging.LogRecord;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Formatter_2_6_MockUse {

	public Formatter obj;
	public Formatter_2_6_MockUse(Formatter p) {
		obj = p;
		callFormatterMethods();
		callObjectMethods();
	}

	public void callFormatterMethods() {
		LogRecord lr = new LogRecord(Level.INFO, "hey u guys");
		obj.format(lr);
		obj.formatMessage(lr);
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}
