package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.lang;

import java.lang.Integer;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Integer_2_6_MockUse {

	public Integer obj = null;
	public int obj0 = Integer.MAX_VALUE;
	public int obj1 = Integer.MIN_VALUE;
	public int obj2 = Integer.SIZE;
	public java.lang.Class obj3 = Integer.TYPE;
	public Integer_2_6_MockUse() {
		obj = new Integer(
			2);
		obj = new Integer(
			"12");
		callIntegerMethods();
		callObjectMethods();
		callNumberMethods();
	}

	public void callIntegerMethods() {
		obj.equals(new Integer(1));
		obj.byteValue();
		obj.doubleValue();
		obj.floatValue();
		obj.bitCount(2);
		obj.compare(2, 2);
		obj.compareTo(new Integer(1));
		obj.hashCode();
		obj.highestOneBit(2);
		obj.intValue();
		obj.lowestOneBit(2);
		obj.numberOfLeadingZeros(2);
		obj.numberOfTrailingZeros(2);
		obj.parseInt("12");
		obj.parseInt("1", 2);
		obj.reverse(2);
		obj.reverseBytes(2);
		obj.rotateLeft(2, 2);
		obj.rotateRight(2, 2);
		obj.signum(2);
		obj.decode("1");
		obj.valueOf(2);
		obj.valueOf("2");
		obj.valueOf("1", 2);
		obj.toBinaryString(2);
		obj.toHexString(2);
		obj.toOctalString(2);
		obj.toString();
		obj.toString(2);
		obj.toString(2, 2);
		obj.longValue();
		obj.shortValue();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callNumberMethods() {
		obj.byteValue();
		obj.doubleValue();
		obj.floatValue();
		obj.intValue();
		obj.longValue();
		obj.shortValue();
	}
}