package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.lang;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Object_2_6_MockUse {

	public Object obj = null;
	public Object_2_6_MockUse() {
		obj = new Object();
		useObjectMembers(obj);
	}
	
	public void useObjectMembers(Object obj) {
		obj.equals(null);
		obj.getClass();
		obj.hashCode();
		obj.toString();
	}
}