package org.adligo.tests4j_tests.models.shared.dependency_group;

import org.adligo.tests4j.models.shared.dependency_groups.JSE_1_7_Lang;
import org.adligo.tests4j.models.shared.dependency_groups.JSE_1_7_Math;
import org.adligo.tests4j.models.shared.trials.SourceFileScope;
import org.adligo.tests4j.models.shared.trials.Test;
import org.adligo.tests4j_tests.base_trials.SourceFileCountingTrial;

@SourceFileScope (sourceClass=JSE_1_7_Math.class)
public class JSE_1_7_MathTrial extends SourceFileCountingTrial {

	@Test
	public void testConstants() {
		//autogenerated by org.adligo.tests4j_tests.models.shared.dependency_group.PackageClassNameWriter
		assertEquals("java.lang.Appendable",JSE_1_7_Lang.APPENDABLE);
		assertEquals("java.math.BigDecimal",JSE_1_7_Math.BIG_DECIMAL);
		assertEquals("java.math.BigInteger",JSE_1_7_Math.BIG_INTEGER);
		assertEquals("java.math.MathContext",JSE_1_7_Math.MATH_CONTEXT);
		assertEquals("java.math.RoundingMode",JSE_1_7_Math.ROUNDING_MODE);
		assertEquals(JSE_1_7_Math.class.getName(), JSE_1_7_Math.INSTANCE.getClass().getName());
	}
	@Override
	public int getTests() {
		return 1;
	}

	@Override
	public int getAsserts() {
		return 6;
	}

	@Override
	public int getUniqueAsserts() {
		return 6;
	}

}
