package org.adligo.tests4j_tests.models.shared.dependency_group;

import org.adligo.tests4j.models.shared.dependency_groups.JSE_1_7_IO;
import org.adligo.tests4j.models.shared.trials.SourceFileScope;
import org.adligo.tests4j.models.shared.trials.Test;
import org.adligo.tests4j_tests.base_trials.SourceFileCountingTrial;

@SourceFileScope (sourceClass=JSE_1_7_IO.class)
public class JSE_1_7_IOTrial extends SourceFileCountingTrial {

	@Test
	public void testConstants() {
		//autogenerated by org.adligo.tests4j_tests.models.shared.dependency_group.PackageClassNameWriter
		assertEquals("java.io.Closeable",JSE_1_7_IO.CLOSEABLE);
		assertEquals("java.io.DataOutput",JSE_1_7_IO.DATA_OUTPUT);
		assertEquals("java.io.DataInput",JSE_1_7_IO.DATA_INPUT);
		assertEquals("java.io.Externalizable",JSE_1_7_IO.EXTERNALIZABLE);
		assertEquals("java.io.FileFilter",JSE_1_7_IO.FILE_FILTER);
		assertEquals("java.io.FilenameFilter",JSE_1_7_IO.FILENAME_FILTER);
		assertEquals("java.io.Flushable",JSE_1_7_IO.FLUSHABLE);
		assertEquals("java.io.ObjectInput",JSE_1_7_IO.OBJECT_INPUT);
		assertEquals("java.io.ObjectInputValidation",JSE_1_7_IO.OBJECT_INPUT_VALIDATION);
		assertEquals("java.io.ObjectOutput",JSE_1_7_IO.OBJECT_OUTPUT);
		assertEquals("java.io.ObjectStreamConstants",JSE_1_7_IO.OBJECT_STREAM_CONSTANTS);
		assertEquals("java.io.Serializable",JSE_1_7_IO.SERIALIZABLE);
		assertEquals("java.io.BufferedInputStream",JSE_1_7_IO.BUFFERED_INPUT_STREAM);
		assertEquals("java.io.BufferedOutputStream",JSE_1_7_IO.BUFFERED_OUTPUT_STREAM);
		assertEquals("java.io.BufferedReader",JSE_1_7_IO.BUFFERED_READER);
		assertEquals("java.io.BufferedWriter",JSE_1_7_IO.BUFFERED_WRITER);
		assertEquals("java.io.ByteArrayInputStream",JSE_1_7_IO.BYTE_ARRAY_INPUT_STREAM);
		assertEquals("java.io.ByteArrayOutputStream",JSE_1_7_IO.BYTE_ARRAY_OUTPUT_STREAM);
		assertEquals("java.io.CharArrayReader",JSE_1_7_IO.CHAR_ARRAY_READER);
		assertEquals("java.io.CharArrayWriter",JSE_1_7_IO.CHAR_ARRAY_WRITER);
		assertEquals("java.io.Console",JSE_1_7_IO.CONSOLE);
		assertEquals("java.io.DataInputStream",JSE_1_7_IO.DATA_INPUT_STREAM);
		assertEquals("java.io.DataOutputStream",JSE_1_7_IO.DATA_OUTPUT_STREAM);
		assertEquals("java.io.File",JSE_1_7_IO.FILE);
		assertEquals("java.io.FileDescriptor",JSE_1_7_IO.FILE_DESCRIPTOR);
		assertEquals("java.io.FileInputStream",JSE_1_7_IO.FILE_INPUT_STREAM);
		assertEquals("java.io.FileOutputStream",JSE_1_7_IO.FILE_OUTPUT_STREAM);
		assertEquals("java.io.FilePermission",JSE_1_7_IO.FILE_PERMISSION);
		assertEquals("java.io.FileReader",JSE_1_7_IO.FILE_READER);
		assertEquals("java.io.FileWriter",JSE_1_7_IO.FILE_WRITER);
		assertEquals("java.io.FilterInputStream",JSE_1_7_IO.FILTER_INPUT_STREAM);
		assertEquals("java.io.FilterOutputStream",JSE_1_7_IO.FILTER_OUTPUT_STREAM);
		assertEquals("java.io.FilterReader",JSE_1_7_IO.FILTER_READER);
		assertEquals("java.io.FilterWriter",JSE_1_7_IO.FILTER_WRITER);
		assertEquals("java.io.InputStream",JSE_1_7_IO.INPUT_STREAM);
		assertEquals("java.io.InputStreamReader",JSE_1_7_IO.INPUT_STREAM_READER);
		assertEquals("java.io.LineNumberInputStream",JSE_1_7_IO.LINE_NUMBER_INPUT_STREAM);
		assertEquals("java.io.LineNumberReader",JSE_1_7_IO.LINE_NUMBER_READER);
		assertEquals("java.io.ObjectInputStream",JSE_1_7_IO.OBJECT_INPUT_STREAM);
		assertEquals("java.io.ObjectInputStream$GetField",JSE_1_7_IO.OBJECT_INPUT_STREAM_GET_FIELD);
		assertEquals("java.io.ObjectOutputStream",JSE_1_7_IO.OBJECT_OUTPUT_STREAM);
		assertEquals("java.io.ObjectOutputStream$PutField",JSE_1_7_IO.OBJECT_OUTPUT_STREAM_PUT_FIELD);
		assertEquals("java.io.ObjectStreamClass",JSE_1_7_IO.OBJECT_STREAM_CLASS);
		assertEquals("java.io.ObjectStreamField",JSE_1_7_IO.OBJECT_STREAM_FIELD);
		assertEquals("java.io.OutputStream",JSE_1_7_IO.OUTPUT_STREAM);
		assertEquals("java.io.OutputStreamWriter",JSE_1_7_IO.OUTPUT_STREAM_WRITER);
		assertEquals("java.io.PipedInputStream",JSE_1_7_IO.PIPED_INPUT_STREAM);
		assertEquals("java.io.PipedOutputStream",JSE_1_7_IO.PIPED_OUTPUT_STREAM);
		assertEquals("java.io.PipedReader",JSE_1_7_IO.PIPED_READER);
		assertEquals("java.io.PipedWriter",JSE_1_7_IO.PIPED_WRITER);
		assertEquals("java.io.PrintStream",JSE_1_7_IO.PRINT_STREAM);
		assertEquals("java.io.PrintWriter",JSE_1_7_IO.PRINT_WRITER);
		assertEquals("java.io.PushbackInputStream",JSE_1_7_IO.PUSHBACK_INPUT_STREAM);
		assertEquals("java.io.PushbackReader",JSE_1_7_IO.PUSHBACK_READER);
		assertEquals("java.io.RandomAccessFile",JSE_1_7_IO.RANDOM_ACCESS_FILE);
		assertEquals("java.io.Reader",JSE_1_7_IO.READER);
		assertEquals("java.io.SequenceInputStream",JSE_1_7_IO.SEQUENCE_INPUT_STREAM);
		assertEquals("java.io.SerializablePermission",JSE_1_7_IO.SERIALIZABLE_PERMISSION);
		assertEquals("java.io.StreamTokenizer",JSE_1_7_IO.STREAM_TOKENIZER);
		assertEquals("java.io.StringBufferInputStream",JSE_1_7_IO.STRING_BUFFER_INPUT_STREAM);
		assertEquals("java.io.StringReader",JSE_1_7_IO.STRING_READER);
		assertEquals("java.io.StringWriter",JSE_1_7_IO.STRING_WRITER);
		assertEquals("java.io.Writer",JSE_1_7_IO.WRITER);
		assertEquals("java.io.CharConversionException",JSE_1_7_IO.CHAR_CONVERSION_EXCEPTION);
		assertEquals("java.io.EOFException",JSE_1_7_IO.EOFEXCEPTION);
		assertEquals("java.io.FileNotFoundException",JSE_1_7_IO.FILE_NOT_FOUND_EXCEPTION);
		assertEquals("java.lang.InterruptedException",JSE_1_7_IO.INTERRUPTED_EXCEPTION);
		assertEquals("java.io.InvalidClassException",JSE_1_7_IO.INVALID_CLASS_EXCEPTION);
		assertEquals("java.io.InvalidObjectException",JSE_1_7_IO.INVALID_OBJECT_EXCEPTION);
		assertEquals("java.io.IOException",JSE_1_7_IO.IOEXCEPTION);
		assertEquals("java.io.NotActiveException",JSE_1_7_IO.NOT_ACTIVE_EXCEPTION);
		assertEquals("java.io.NotSerializableException",JSE_1_7_IO.NOT_SERIALIZABLE_EXCEPTION);
		assertEquals("java.io.ObjectStreamException",JSE_1_7_IO.OBJECT_STREAM_EXCEPTION);
		assertEquals("java.io.OptionalDataException",JSE_1_7_IO.OPTIONAL_DATA_EXCEPTION);
		assertEquals("java.io.StreamCorruptedException",JSE_1_7_IO.STREAM_CORRUPTED_EXCEPTION);
		assertEquals("java.io.SyncFailedException",JSE_1_7_IO.SYNC_FAILED_EXCEPTION);
		assertEquals("java.io.UnsupportedEncodingException",JSE_1_7_IO.UNSUPPORTED_ENCODING_EXCEPTION);
		assertEquals("java.io.UTFDataFormatException",JSE_1_7_IO.UTFDATA_FORMAT_EXCEPTION);
		assertEquals("java.io.WriteAbortedException",JSE_1_7_IO.WRITE_ABORTED_EXCEPTION);
		assertEquals("java.io.IOError",JSE_1_7_IO.IOERROR);
		assertEquals(JSE_1_7_IO.class.getName(), JSE_1_7_IO.INSTANCE.getClass().getName());
	}
	@Override
	public int getTests() {
		return 1;
	}

	@Override
	public int getAsserts() {
		return 81;
	}

	@Override
	public int getUniqueAsserts() {
		return 81;
	}

}
