package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.sql;

import java.sql.Date;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Date_2_6_MockUse {

	public Date obj = null;
	public Date_2_6_MockUse() {
		obj = new Date(
			2, 2, 2);
		obj = new Date(
			3L);
		
		callObjectMethods();
		callUtilDateMethods();
		callDateMethods();
	}

	public void callDateMethods() {
		try {
			obj.getHours();
		} catch (IllegalArgumentException x) {
			//this crap is why I suggest not using
			//java.sql.Date use SQL-Types(DateTimes or Timestamps) in the Database
			//and java.util.Date or Long for the member value/attribute/field.
		}
		try {
			obj.getMinutes();
		} catch (IllegalArgumentException x) {
			
		}
		try {
			obj.getSeconds();
		} catch (IllegalArgumentException x) {
			
		}
		try {
			obj.setHours(2);
		} catch (IllegalArgumentException x) {
			
		}
		try {
			obj.setMinutes(2);
		} catch (IllegalArgumentException x) {
			
		}
		try {
			obj.setSeconds(2);
		} catch (IllegalArgumentException x) {
			
		}
		try {
			obj.setTime(3L);
		} catch (IllegalArgumentException x) {
			
		}
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callUtilDateMethods() {
		obj.after(new Date(2));
		obj.before(new Date(2));
		obj.compareTo(new Date(2));
		obj.getDate();
		obj.getDay();
		try {
			obj.getHours();
		} catch (IllegalArgumentException x) {
			//this crap is why I suggest not using
			//java.sql.Date use SQL-Types(DateTimes or Timestamps) in the Database
			//and java.util.Date or Long for the member value/attribute/field.
		}
		try {
			obj.getMinutes();
		} catch (IllegalArgumentException x) {
			
		}
		obj.getMonth();
		try {
			obj.getSeconds();
		} catch (IllegalArgumentException x) {
			
		}
		obj.getTimezoneOffset();
		obj.getYear();
		obj.clone();
		obj.toGMTString();
		obj.toLocaleString();
		obj.UTC(2, 2, 2, 2, 2, 2);
		obj.getTime();
		obj.parse("12/31/1969");
		obj.setDate(2);
		try {
			obj.setHours(2);
		} catch (IllegalArgumentException x) {
			
		}
		try {
			obj.setMinutes(2);
		} catch (IllegalArgumentException x) {
			
		}
		obj.setMonth(2);
		try {
			obj.setSeconds(2);
		} catch (IllegalArgumentException x) {
			
		}
		obj.setTime(3L);
		obj.setYear(2);
		obj.valueOf("1969-12-31");
	}
}
