package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.util;

import java.util.ArrayList;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class ArrayList_2_6_MockUse {

	public ArrayList obj = null;
	public ArrayList_2_6_MockUse() {
		obj = new ArrayList();
		obj = new ArrayList(
			2);
		obj = new ArrayList(
			new ArrayList());
		callArrayListMethods();
		callObjectMethods();
		callAbstractCollectionMethods();
		callAbstractListMethods();
	}

	public void callArrayListMethods() {
		obj.add(new Object());
		obj.add(new Object());
		obj.add(new Object());
		obj.add(new Object());
		obj.add(new Object());
		obj.add(new Object());
		obj.add(new Object());
		
		obj.addAll(2, new ArrayList());
		obj.contains(new Object());
		obj.isEmpty();
		obj.remove(new Object());
		obj.removeAll(new ArrayList());
		obj.retainAll(new ArrayList());
		obj.indexOf(new Object());
		obj.lastIndexOf(new Object());
		obj.size();
		obj.clone();
		obj.add(new Object());
		obj.add(new Object());
		obj.add(new Object());
		obj.get(2);
		obj.remove(2);
		obj.set(0, new Object());
		obj.subList(2, 2);
		obj.listIterator();
		obj.listIterator(2);
		obj.add(2, new Object());
		obj.ensureCapacity(2);
		obj.trimToSize();
	}
	
	public void callAbstractListMethods() {
		obj.add(new Object());
		obj.addAll(0, new ArrayList());
		obj.indexOf(new Object());
		obj.lastIndexOf(new Object());
		obj.get(0);
		obj.remove(0);
		obj.add(new Object());
		obj.set(0, new Object());
		obj.iterator();
		obj.subList(0, 1);
		obj.listIterator();
		obj.listIterator(1);
		obj.add(1, new Object());
		obj.clear();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callAbstractCollectionMethods() {
		obj.toArray();
		obj.toArray(new Object[] {});
		obj.add(new Object());
		obj.addAll(new ArrayList());
		obj.contains(new Object());
		obj.containsAll(new ArrayList());
		obj.isEmpty();
		obj.remove(new Object());
		obj.removeAll(new ArrayList());
		obj.retainAll(new ArrayList());
		obj.size();
		obj.iterator();
		obj.clear();
	}
}