package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.util;

import java.util.Collection;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Collection_2_6_MockUse {

	public Collection_2_6_MockUse(Collection p) {
		p.toArray();
		p.toArray(null);
		p.add(new Object());
		p.addAll(null);
		p.contains(new Object());
		p.containsAll(null);
		p.equals(new Object());
		p.isEmpty();
		p.remove(new Object());
		p.removeAll(null);
		p.retainAll(null);
		p.hashCode();
		p.size();
		p.iterator();
		p.clear();
	}
}