package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.util;

import java.util.Comparator;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Comparator_2_6_MockUse {

	public Comparator_2_6_MockUse(Comparator p) {
		p.equals(new Object());
		p.compare(new Object(), new Object());
	}
}