package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.util;

import java.util.Map.Entry;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Entry_2_6_MockUse {

	public Entry_2_6_MockUse(Entry p) {
		p.equals(new Object());
		p.hashCode();
		p.getKey();
		p.getValue();
		p.setValue(new Object());
	}
}