package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.util;

import java.util.Enumeration;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Enumeration_2_6_MockUse {

	public Enumeration_2_6_MockUse(Enumeration p) {
		p.hasMoreElements();
		p.nextElement();
	}
}