package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.util;

import java.util.MissingResourceException;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class MissingResourceException_2_6_MockUse {

	public MissingResourceException obj = null;
	public MissingResourceException_2_6_MockUse() {
		obj = new MissingResourceException(
			"string", "string", "string");
		callMissingResourceExceptionMethods();
		callObjectMethods();
		callThrowableMethods();
	}

	public void callMissingResourceExceptionMethods() {
		obj.getClassName();
		obj.getKey();
	}
	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callObjectMethods() {
		obj.equals(null);
		obj.getClass();
		obj.hashCode();
		obj.toString();
	}
	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callThrowableMethods() {
		obj.getStackTrace();
		obj.getSuppressed();
		obj.getLocalizedMessage();
		obj.getMessage();
		obj.toString();
		obj.fillInStackTrace();
		obj.getCause();
		
		obj = new MissingResourceException(
				"string", "string", "string");
		obj.initCause(new Throwable());
		obj = new MissingResourceException(
				"string", "string", "string");
		obj.addSuppressed(new RuntimeException());
		obj.printStackTrace();
		obj.printStackTrace(System.out);
		obj.setStackTrace(new StackTraceElement[] {});
	}
}