package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.util;

import java.util.Queue;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/

public class Queue_2_6_MockUse {

	public Queue_2_6_MockUse(Queue<Object> p) {
		p.add(new Object());
		p.offer(new Object());
		p.element();
		p.peek();
		p.poll();
		p.remove();
	}
}