package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.util;

import java.util.HashMap;
import java.util.SortedMap;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
@SuppressWarnings({ "unchecked", "rawtypes" })
public class SortedMap_2_6_MockUse {

	
	public SortedMap_2_6_MockUse(SortedMap p) {
		callMapMethods(p);
		
		p.firstKey();
		p.lastKey();
		p.values();
		p.comparator();
		p.entrySet();
		p.keySet();
		p.headMap(new Object());
		p.subMap(new Object(), new Object());
		p.tailMap(new Object());
	}

	public void callMapMethods(SortedMap p) {
		p.containsKey(new Object());
		p.containsValue(new Object());
		p.equals(new Object());
		p.isEmpty();
		p.hashCode();
		p.size();
		p.get(new Object());
		p.put(new Object(), new Object());
		p.remove(new Object());
		p.values();
		p.entrySet();
		p.keySet();
		p.clear();
		p.putAll(new HashMap());
	}
}