package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.util;

import java.util.ArrayList;
import java.util.Vector;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
@SuppressWarnings({"rawtypes","unchecked"})
public class Vector_2_6_MockUse {

	
	public Vector obj = null;
	public Vector_2_6_MockUse() {
		obj = new Vector();
		obj = new Vector(
			2);
		obj = new Vector(
			2, 2);
		obj = new Vector(
			new ArrayList());
		callVectorMethods();
		callObjectMethods();
		callAbstractCollectionMethods();
		callAbstractListMethods();
	}

	public void callVectorMethods() {
		obj.add(new Object());
		obj.add(new Object());
		obj.add(new Object());
		obj.add(new Object());
		obj.add(new Object());
		
		obj.removeElement(new Object());
		obj.indexOf(new Object());
		obj.indexOf(new Object(), 2);
		obj.lastIndexOf(new Object());
		obj.lastIndexOf(new Object(), 2);
		obj.clone();
		obj.elementAt(2);
		obj.firstElement();
		obj.lastElement();
		obj.set(2, new Object());
		obj.toString();
		obj.elements();
		obj.subList(2, 2);
		obj.add(2, new Object());
		obj.addElement(new Object());
		obj.copyInto(new Object[10]);
		obj.ensureCapacity(2);
		obj.insertElementAt(new Object(), 2);
		obj.setElementAt(new Object(), 2);
		obj.removeElementAt(2);
		obj.removeAllElements();
		
		obj.capacity();
		obj.setSize(2);
		obj.trimToSize();
	}

	public void callAbstractListMethods() {
		obj.add(new Object());
		obj.addAll(0, new ArrayList());
		obj.equals(new Object());
		obj.hashCode();
		obj.indexOf(new Object());
		obj.lastIndexOf(new Object());
		obj.get(0);
		obj.remove(0);
		obj.add(new Object());
		obj.set(0, new Object());
		obj.iterator();
		obj.subList(0, 1);
		obj.listIterator();
		obj.listIterator(1);
		obj.add(1, new Object());
		obj.clear();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callAbstractCollectionMethods() {
		obj.toArray();
		obj.toArray(new Object[] {});
		obj.add(new Object());
		obj.addAll(new ArrayList());
		obj.contains(new Object());
		obj.containsAll(new ArrayList());
		obj.isEmpty();
		obj.remove(new Object());
		obj.removeAll(new ArrayList());
		obj.retainAll(new ArrayList());
		obj.size();
		obj.iterator();
		obj.clear();
	}
}
