package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.lang;

import java.lang.CharSequence;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class CharSequence_2_6_MockUse {

	public CharSequence_2_6_MockUse(CharSequence p) {
		p.charAt(2);
		p.length();
		p.subSequence(2, 2);
		p.toString();
	}
}