package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.lang;

import java.lang.Cloneable;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Cloneable_2_6_MockUse {

	public Cloneable_2_6_MockUse(Cloneable p) {
	}
}