package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.lang;

import java.lang.Iterable;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Iterable_2_6_MockUse {

	public Iterable_2_6_MockUse(Iterable p) {
		p.iterator();
	}
}