package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.lang;

import java.lang.Class;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Class_2_6_MockUse {

	public Class obj = null;
	public Class_2_6_MockUse(Class<?> c) {
		obj = c;
		callClassMethods();
		callObjectMethods();
	}

	public void callClassMethods() {
		obj.desiredAssertionStatus();
		obj.isArray();
		obj.isEnum();
		obj.isInterface();
		obj.isPrimitive();
		obj.getSuperclass();
		obj.getComponentType();
		obj.getEnumConstants();
		obj.getName();
		obj.getSimpleName();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}