package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.lang;

import java.lang.Double;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Double_2_6_MockUse {

	public Double obj = null;
	public int obj0 = Double.MAX_EXPONENT;
	public double obj1 = Double.MAX_VALUE;
	public int obj2 = Double.MIN_EXPONENT;
	public double obj3 = Double.MIN_NORMAL;
	public double obj4 = Double.MIN_VALUE;
	public double obj5 = Double.NEGATIVE_INFINITY;
	public double obj6 = Double.NaN;
	public double obj7 = Double.POSITIVE_INFINITY;
	public int obj8 = Double.SIZE;
	public java.lang.Class obj9 = Double.TYPE;
	public Double_2_6_MockUse() {
		obj = new Double(
			0.1);
		obj = new Double(
			"1.1");
		callDoubleMethods();
		callObjectMethods();
		callNumberMethods();
	}

	public void callDoubleMethods() {
		obj.equals(new Object());
		obj.isNaN();
		obj.isNaN(0.1);
		obj.byteValue();
		obj.doubleValue();
		obj.parseDouble("1.1");
		obj.floatValue();
		obj.compare(0.1, 0.1);
		obj.compareTo(new Double(1.1));
		obj.intValue();
		obj.valueOf(0.1);
		obj.valueOf("0.1");
		obj.toString(0.1);
		obj.longValue();
		obj.shortValue();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callNumberMethods() {
		obj.byteValue();
		obj.doubleValue();
		obj.floatValue();
		obj.intValue();
		obj.longValue();
		obj.shortValue();
	}
}