package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.lang;

import java.lang.Long;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Long_2_6_MockUse {

	public Long obj = null;
	public long obj0 = Long.MAX_VALUE;
	public long obj1 = Long.MIN_VALUE;
	public int obj2 = Long.SIZE;
	public java.lang.Class obj3 = Long.TYPE;
	public Long_2_6_MockUse() {
		obj = new Long(
			"13");
		obj = new Long(
			3L);
		callLongMethods();
		callObjectMethods();
		callNumberMethods();
	}

	public void callLongMethods() {
		obj.equals(new Object());
		obj.byteValue();
		obj.doubleValue();
		obj.floatValue();
		obj.bitCount(3L);
		obj.compare(3L, 3L);
		obj.compareTo(new Long(13));
		obj.hashCode();
		obj.intValue();
		obj.numberOfLeadingZeros(3L);
		obj.numberOfTrailingZeros(3L);
		obj.signum(3L);
		obj.decode("13");
		obj.valueOf("13");
		obj.valueOf("1", Character.MIN_RADIX);
		obj.valueOf(3L);
		obj.toBinaryString(3L);
		obj.toHexString(3L);
		obj.toOctalString(3L);
		obj.toString();
		obj.toString(3L);
		obj.toString(3L, 2);
		obj.highestOneBit(3L);
		obj.longValue();
		obj.lowestOneBit(3L);
		obj.parseLong("13");
		obj.parseLong("1", Character.MIN_RADIX);
		obj.reverse(3L);
		obj.reverseBytes(3L);
		obj.rotateLeft(3L, 2);
		obj.rotateRight(3L, 2);
		obj.shortValue();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callNumberMethods() {
		obj.byteValue();
		obj.doubleValue();
		obj.floatValue();
		obj.intValue();
		obj.longValue();
		obj.shortValue();
	}
}