package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.lang;


/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class NoSuchFieldError_2_6_MockUse {

	public NoSuchFieldError obj = null;
	public NoSuchFieldError_2_6_MockUse() {
	  obj = new NoSuchFieldError();
		obj = new NoSuchFieldError(
			"string");
		callObjectMethods();
		callThrowableMethods();
	}


	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callObjectMethods() {
		obj.equals(null);
		obj.getClass();
		obj.hashCode();
		obj.toString();
	}
	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callThrowableMethods() {
		obj = new NoSuchFieldError();
		obj.initCause(new Throwable("hmm"));
		obj = new NoSuchFieldError();
		obj.addSuppressed(new Throwable());
		
		obj.getStackTrace();
		obj.getSuppressed();
		obj.getLocalizedMessage();
		obj.getMessage();
		obj.toString();
		obj.fillInStackTrace();
		obj.getCause();
		
		obj.printStackTrace();
		obj.printStackTrace(System.out);
		obj.setStackTrace(new StackTraceElement[] {});
	}
}