package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.lang;

import java.lang.Number;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Number_2_6_MockUse {

	public Number obj = null;
	public Number_2_6_MockUse(Number n) {
		obj = n;
		callNumberMethods();
		callObjectMethods();
	}

	public void callNumberMethods() {
		obj.byteValue();
		obj.doubleValue();
		obj.floatValue();
		obj.intValue();
		obj.longValue();
		obj.shortValue();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}