package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.lang;


/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class System_2_6_MockUse {

	public System obj = null;
	public java.io.PrintStream obj0 = System.err;
	public java.io.PrintStream obj2 = System.out;
	public System_2_6_MockUse() {
		callSystemMethods();
	}

	@SuppressWarnings("static-access")
	public void callSystemMethods() {
		obj.identityHashCode(new Object());
		obj.getProperty("string", "string");
		obj.currentTimeMillis();
		obj.arraycopy(new Object[] {new Character('a')}, 0, new Object[1], 0, 1);
		obj.gc();
		obj.setErr(System.out);
		obj.setOut(System.out);
	}
}