package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.math;

import java.math.MathContext;
import java.math.RoundingMode;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class MathContext_2_6_MockUse {

	public MathContext obj = null;
	public java.math.MathContext obj0 = MathContext.DECIMAL128;
	public java.math.MathContext obj1 = MathContext.DECIMAL32;
	public java.math.MathContext obj2 = MathContext.DECIMAL64;
	public java.math.MathContext obj3 = MathContext.UNLIMITED;
	public MathContext_2_6_MockUse() {
		obj = new MathContext(
			2);
		obj = new MathContext(
			2, RoundingMode.HALF_UP);
		obj = new MathContext(
			"precision=2 roundingMode=HALF_UP");
		callMathContextMethods();
		callObjectMethods();
	}

	public void callMathContextMethods() {
		obj.equals(new Object());
		obj.getPrecision();
		obj.hashCode();
		obj.toString();
		obj.getRoundingMode();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}
