package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.math;

import java.math.RoundingMode;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class RoundingMode_2_6_MockUse {

	public RoundingMode obj = RoundingMode.HALF_DOWN;
	public java.math.RoundingMode obj0 = RoundingMode.CEILING;
	public java.math.RoundingMode obj1 = RoundingMode.DOWN;
	public java.math.RoundingMode obj2 = RoundingMode.FLOOR;
	public java.math.RoundingMode obj3 = RoundingMode.HALF_DOWN;
	public java.math.RoundingMode obj4 = RoundingMode.HALF_EVEN;
	public java.math.RoundingMode obj5 = RoundingMode.HALF_UP;
	public java.math.RoundingMode obj6 = RoundingMode.UNNECESSARY;
	public java.math.RoundingMode obj7 = RoundingMode.UP;
	public RoundingMode_2_6_MockUse() {
		callRoundingModeMethods();
		callObjectMethods();
		callEnumMethods();
	}

	public void callRoundingModeMethods() {
		obj.values();
		obj.valueOf(2);
		obj.valueOf("HALF_UP");
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callEnumMethods() {
		obj.compareTo(RoundingMode.HALF_UP);
		obj.hashCode();
		obj.ordinal();
		obj.getDeclaringClass();
		obj.valueOf(RoundingMode.class, "HALF_UP");
		obj.name();
		obj.toString();
	}
}
