package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.annotation;

import java.lang.annotation.Annotation;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Annotation_2_6_MockUse {

	public Annotation_2_6_MockUse(Annotation p) {
		p.equals(new Object());
		p.hashCode();
		p.annotationType();
		p.toString();
	}
}