package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;


/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/

@Retention(value=RetentionPolicy.RUNTIME)
@Documented
public @interface Documented_2_6_Annotation {
	
	
}