package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.annotation;

import java.lang.annotation.IncompleteAnnotationException;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class IncompleteAnnotationException_2_6_MockUse {

	public IncompleteAnnotationException obj = null;
	public IncompleteAnnotationException_2_6_MockUse() {
		obj = new IncompleteAnnotationException(
			Override.class, "string");
		callIncompleteAnnotationExceptionMethods();
		callObjectMethods();
		callThrowableMethods();
	}

	public void callIncompleteAnnotationExceptionMethods() {
		obj.annotationType();
		obj.elementName();
	}
	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callObjectMethods() {
		obj.equals(null);
		obj.getClass();
		obj.hashCode();
		obj.toString();
	}
	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callThrowableMethods() {
		obj.getStackTrace();
		obj.getSuppressed();
		obj.getLocalizedMessage();
		obj.getMessage();
		obj.toString();
		obj.fillInStackTrace();
		obj.getCause();
		
		obj = new IncompleteAnnotationException(Override.class, "string");
		obj.initCause(new Throwable());
		obj = new IncompleteAnnotationException(Override.class, "string");
		obj.addSuppressed(new RuntimeException());
		obj.printStackTrace();
		obj.printStackTrace(System.out);
		obj.setStackTrace(new StackTraceElement[] {});
	}

}