package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.annotation;
import java.lang.annotation.Retention;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Retention_2_6_MockUse {

	public Retention_2_6_MockUse(Retention p) {
		p.value();
	}
}