package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.lang;

import java.lang.Boolean;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Boolean_2_6_MockUse {

	public Boolean obj = null;
	public java.lang.Boolean obj0 = Boolean.FALSE;
	public java.lang.Boolean obj1 = Boolean.TRUE;
	public java.lang.Class obj2 = Boolean.TYPE;
	public Boolean_2_6_MockUse() {
		obj = new Boolean(
			true);
		obj = new Boolean(
			"false");
		callBooleanMethods();
		callObjectMethods();
	}

	public void callBooleanMethods() {
		obj.booleanValue();
		obj.parseBoolean("true");
		obj.compare(true, true);
		obj.compareTo(new Boolean(true));
		obj.valueOf(true);
		obj.valueOf("true");
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}