package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.lang;

import java.lang.Enum;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Enum_2_6_MockUse {

	public Enum obj = null;
	public Enum_2_6_MockUse() {
		obj = Enum_2_6_Mock.HEY;
		callEnumMethods();
		callObjectMethods();
	}

	public void callEnumMethods() {
		obj.compareTo(Enum_2_6_Mock.HEY);
		obj.ordinal();
		obj.getDeclaringClass();
		obj.valueOf(Enum_2_6_Mock.class, "HEY");
		obj.name();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}