package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.lang;

import java.lang.Math;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Math_2_6_MockUse {

	public double Math0 = Math.E;
	public double Math1 = Math.PI;
	public Math_2_6_MockUse() {
		callMathMethods();
	}

	public void callMathMethods() {
		Math.abs(0.1);
		Math.acos(0.1);
		Math.asin(0.1);
		Math.atan(0.1);
		Math.atan2(0.1, 0.1);
		Math.cbrt(0.1);
		Math.ceil(0.1);
		Math.copySign(0.1, 0.1);
		Math.cos(0.1);
		Math.cosh(0.1);
		Math.exp(0.1);
		Math.expm1(0.1);
		Math.floor(0.1);
		Math.hypot(0.1, 0.1);
		Math.log(0.1);
		Math.log10(0.1);
		Math.log1p(0.1);
		Math.max(0.1, 0.1);
		Math.min(0.1, 0.1);
		Math.pow(0.1, 0.1);
		Math.random();
		Math.rint(0.1);
		Math.scalb(0.1, 2);
		Math.signum(0.1);
		Math.sin(0.1);
		Math.sinh(0.1);
		Math.sqrt(0.1);
		Math.tan(0.1);
		Math.tanh(0.1);
		Math.toDegrees(0.1);
		Math.toRadians(0.1);
		Math.abs((float) 0.2);
		Math.copySign((float) 0.2, (float) 0.2);
		Math.max((float) 0.2, (float) 0.2);
		Math.min((float) 0.2, (float) 0.2);
		Math.scalb((float) 0.2, 2);
		Math.signum((float) 0.2);
		Math.abs(2);
		Math.max(2, 2);
		Math.min(2, 2);
		Math.round((float) 0.2);
		Math.abs(3L);
		Math.max(3L, 3L);
		Math.min(3L, 3L);
		Math.round(0.1);
	}
}