package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.lang;

import java.lang.StringBuffer;
import java.nio.CharBuffer;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class StringBuffer_2_6_MockUse {

	public StringBuffer obj = null;
	public StringBuffer_2_6_MockUse() {
		obj = new StringBuffer();
		obj = new StringBuffer(
			2);
		obj = new StringBuffer(
				CharBuffer.allocate(1));
		obj = new StringBuffer(
			"string");
		callStringBufferMethods();
		callObjectMethods();
	}

	public void callStringBufferMethods() {
		obj.charAt(2);
		obj.capacity();
		obj.indexOf("string");
		obj.indexOf("string", 2);
		obj.lastIndexOf("string");
		obj.lastIndexOf("string", 2);
		obj.length();
		obj.append(new char[] {'a','b','c'});
		obj.append(new char[] {'a','b','c'}, 0, 1);
		obj.append(true);
		obj.append('c');
		obj.append(0.1);
		obj.append((float) 0.2);
		obj.append(2);
		obj.append(CharBuffer.allocate(1));
		obj.append(new StringBuffer());
		obj.append("charSequence", 2, 2);
		obj.append(new Object());
		obj.append("string");
		obj.append(new char[] {'a','b','c'});
		obj.append(3L);
		obj.delete(2, 2);
		obj.deleteCharAt(2);
		obj.insert(2, new char[] {'a','b','c'});
		obj.insert(2, new char[] {'a','b','c'}, 0, 1);
		obj.insert(2, true);
		obj.insert(2, 'c');
		obj.insert(2, 0.1);
		obj.insert(2, (float) 0.2);
		obj.insert(2, 2);
		obj.insert(2, CharBuffer.allocate(1));
		obj.insert(2, CharBuffer.allocate(1), 0, 1);
		obj.insert(2, new Object());
		obj.insert(2, "string");
		obj.insert(2, 3L);
		obj.replace(2, 2, "string");
		obj.reverse();
		obj.append('c');
		obj.append("charSequence");
		obj.append("charSequence", 2, 2);
		obj.subSequence(2, 2);
		obj.substring(2);
		obj.substring(2, 2);
		obj.toString();
		obj.append(new char[] {'a','b','c'});
		obj.append(new char[] {'a','b','c'}, 0, 1);
		obj.append(true);
		obj.append('c');
		obj.append(0.1);
		obj.append((float) 0.2);
		obj.append(2);
		obj.append("charSequence");
		obj.append("charSequence", 2, 2);
		obj.append(new Object());
		obj.append("string");
		obj.append(new char[] {'a','b','c'});
		obj.append(3L);
		obj.delete(2, 2);
		obj.deleteCharAt(2);
		obj.insert(2, new char[] {'a','b','c'});
		obj.insert(2, new char[] {'a','b','c'}, 0, 1);
		obj.insert(2, true);
		obj.insert(2, 'c');
		obj.insert(2, 0.1);
		obj.insert(2, (float) 0.2);
		obj.insert(2, 2);
		obj.insert(2, "charSequence");
		obj.insert(2, "charSequence", 2, 2);
		obj.insert(2, new Object());
		obj.insert(2, "string");
		obj.insert(2, 3L);
		obj.replace(2, 2, "string");
		obj.reverse();
		obj.ensureCapacity(2);
		obj.getChars(2, 2, new char[] {'a','b','c'}, 2);
		obj.setCharAt(2, 'c');
		obj.setLength(2);
		obj.trimToSize();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}