package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.lang;


/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Void_2_6_MockUse {

	public Void obj = null;
	public java.lang.Class obj0 = Void.TYPE;
}