package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.math;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.math.MathContext;
import java.math.RoundingMode;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class BigDecimal_2_6_MockUse {

	public BigDecimal obj = null;
	public java.math.BigDecimal obj0 = BigDecimal.ONE;
	public int obj1 = BigDecimal.ROUND_CEILING;
	public int obj2 = BigDecimal.ROUND_DOWN;
	public int obj3 = BigDecimal.ROUND_FLOOR;
	public int obj4 = BigDecimal.ROUND_HALF_DOWN;
	public int obj5 = BigDecimal.ROUND_HALF_EVEN;
	public int obj6 = BigDecimal.ROUND_HALF_UP;
	public int obj7 = BigDecimal.ROUND_UNNECESSARY;
	public int obj8 = BigDecimal.ROUND_UP;
	public java.math.BigDecimal obj9 = BigDecimal.TEN;
	public java.math.BigDecimal obj10 = BigDecimal.ZERO;
	
	public BigDecimal_2_6_MockUse() {
		obj = new BigDecimal(
				new BigInteger("1"));
		obj = new BigDecimal(
				new BigInteger("1"), 2);
		obj = new BigDecimal(
				new BigInteger("1"), 2, new MathContext(2));
		obj = new BigDecimal(new BigInteger("1"), new MathContext(2));
		
		obj = new BigDecimal("1".toCharArray());
		obj = new BigDecimal("1".toCharArray(), 0, 1);
		obj = new BigDecimal("1".toCharArray(), 0, 1, new MathContext(2));
		obj = new BigDecimal("1".toCharArray(), new MathContext(2));
		
		obj = new BigDecimal(
			0.1);
		obj = new BigDecimal(
			0.1, new MathContext(2));
		obj = new BigDecimal(
			2);
		obj = new BigDecimal(
			2, new MathContext(2));
		obj = new BigDecimal(
			"1");
		obj = new BigDecimal(
			"1",  new MathContext(2));
		
		
		obj = new BigDecimal(
			3L);
		obj = new BigDecimal(
			3L,  new MathContext(2));
		callBigDecimalMethods();
		callObjectMethods();
		callNumberMethods();
	}

	@SuppressWarnings("static-access")
	public void callBigDecimalMethods() {
		obj.divideAndRemainder(new BigDecimal("1"));
		obj.divideAndRemainder(new BigDecimal("1"), new MathContext(2));
		obj.byteValueExact();
		obj.doubleValue();
		obj.floatValue();
		obj.compareTo(new BigDecimal("1"));
		obj.intValue();
		obj.intValueExact();
		obj.precision();
		obj.scale();
		obj.signum();
		obj.toEngineeringString();
		obj.toPlainString();
		obj.abs();
		obj.abs(new MathContext(2));
		obj.add(new BigDecimal("1"));
		obj.add(new BigDecimal("1"), new MathContext(2));
		obj.divide(new BigDecimal("1"));
		obj.divide(new BigDecimal("1"), 2);
		obj.divide(new BigDecimal("1"), 2, 2);
		obj.divide(new BigDecimal("1"), 2, RoundingMode.HALF_UP);
		obj.divide(new BigDecimal("1"));
		obj.divide(new BigDecimal("1"), new MathContext(2));
		obj.divide(new BigDecimal("1"), RoundingMode.HALF_UP);
		obj.divideToIntegralValue(new BigDecimal("1"));
		obj.divideToIntegralValue(new BigDecimal("1"), new MathContext(2));
		obj.max(new BigDecimal("1"));
		obj.min(new BigDecimal("1"));
		obj.movePointLeft(2);
		obj.movePointRight(2);
		obj.multiply(new BigDecimal("1"));
		obj.multiply(new BigDecimal("1"), new MathContext(2));
		obj.negate();
		obj.negate(new MathContext(2));
		obj.plus();
		obj.plus(new MathContext(2));
		obj.pow(2);
		obj.pow(2, new MathContext(2));
		obj.remainder(new BigDecimal("1"));
		obj.remainder(new BigDecimal("1"), new MathContext(2));
		obj.round(new MathContext(2));
		obj.scaleByPowerOfTen(2);
		obj.setScale(2);
		obj.setScale(2, 2);
		obj.setScale(2, RoundingMode.HALF_UP);
		obj.stripTrailingZeros();
		obj.subtract(new BigDecimal("1"));
		obj.subtract(new BigDecimal("1"), new MathContext(2));
		obj.ulp();
		obj.toBigInteger();
		obj.toBigIntegerExact();
		obj.unscaledValue();
		obj.longValue();
		obj.longValueExact();
		obj.shortValueExact();
		obj.valueOf(2.0);
		obj.valueOf(1L);
		obj.valueOf(3L, 2);
	}
	
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callNumberMethods() {
		obj.byteValue();
		obj.doubleValue();
		obj.floatValue();
		obj.intValue();
		obj.longValue();
		obj.shortValue();
	}
}
