package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.logging;

import java.util.logging.Formatter;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.LogRecord;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Handler_2_6_MockUse {

	public Handler obj = null;
	public Handler_2_6_MockUse(Handler p, Formatter fmt) {
		obj = p;
		callHandlerMethods(fmt);
		callObjectMethods();
	}

	public void callHandlerMethods(Formatter fmt) {
		LogRecord lr = new LogRecord(Level.INFO, "hey u guys");
		obj.setLevel(Level.INFO);
		obj.isLoggable(lr);
		obj.getFormatter();
		obj.getLevel();
		obj.close();
		obj.flush();
		obj.publish(lr);
		obj.setFormatter(fmt);
		
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}
