package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.logging;

import java.util.logging.Level;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Level_2_6_MockUse {

	public Level obj = Level.ALL;
	public java.util.logging.Level obj0 = Level.ALL;
	public java.util.logging.Level obj1 = Level.CONFIG;
	public java.util.logging.Level obj2 = Level.FINE;
	public java.util.logging.Level obj3 = Level.FINER;
	public java.util.logging.Level obj4 = Level.FINEST;
	public java.util.logging.Level obj5 = Level.INFO;
	public java.util.logging.Level obj6 = Level.OFF;
	public java.util.logging.Level obj7 = Level.SEVERE;
	public java.util.logging.Level obj8 = Level.WARNING;
	
	public Level_2_6_MockUse() {
		callLevelMethods();
		callObjectMethods();
	}

	public void callLevelMethods() {
		obj.intValue();
		obj.getName();
		obj.parse("INFO");
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}
