package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.sql;

import java.sql.Timestamp;
import java.util.Date;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Timestamp_2_6_MockUse {

	public Timestamp obj = null;
	public Timestamp_2_6_MockUse() {
		obj = new Timestamp(
			2, 2, 2, 2, 2, 2, 2);
		obj = new Timestamp(
			3L);
		callTimestampMethods();
		callObjectMethods();
		callDateMethods();
	}

	public void callTimestampMethods() {
		obj.after(new Timestamp(1L));
		obj.before(new Timestamp(1L));
		obj.equals(new Timestamp(1L));
		obj.compareTo(new Timestamp(1L));
		obj.getNanos();
		obj.valueOf("1969-12-31 00:99:99");
		obj.getTime();
		obj.setNanos(2);
		obj.setTime(3L);
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callDateMethods() {
		obj.after(new Date(0));
		obj.before(new Date(0));
		obj.compareTo(new Date(3));
		obj.getDate();
		obj.getDay();
		obj.getHours();
		obj.getMinutes();
		obj.getMonth();
		obj.getSeconds();
		obj.getTimezoneOffset();
		obj.getYear();
		obj.clone();
		obj.toGMTString();
		obj.toLocaleString();
		obj.UTC(2, 2, 2, 2, 2, 2);
		obj.getTime();
		obj.parse("12/21/1012");
		obj.setDate(2);
		obj.setHours(2);
		obj.setMinutes(2);
		obj.setMonth(2);
		obj.setSeconds(2);
		obj.setTime(3L);
		obj.setYear(2);
		
	}
}
