package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.util;

import java.util.AbstractQueue;
import java.util.PriorityQueue;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class AbstractQueue_2_6_MockUse {

	public AbstractQueue obj = null;
	public AbstractQueue_2_6_MockUse(AbstractQueue  aq) {
		obj = aq;
		callAbstractQueueMethods();
		callObjectMethods();
		callAbstractCollectionMethods();
	}

	public void callAbstractQueueMethods() {
		obj.add(new Object());
		obj.addAll(new PriorityQueue());
		obj.element();
		obj.remove();
		obj.clear();
		obj.offer(new Object());
		obj.poll();
		obj.peek();
		obj.add(new Object());
		obj.remove();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callAbstractCollectionMethods() {
		obj.toArray();
		obj.toArray(new Object[] {});
		obj.add(new Object());
		obj.addAll(new PriorityQueue());
		obj.contains(new Object());
		obj.containsAll(new PriorityQueue());
		obj.isEmpty();
		obj.remove(new Object());
		obj.removeAll(new PriorityQueue());
		obj.retainAll(new PriorityQueue());
		obj.size();
		obj.toString();
		obj.iterator();
		obj.clear();
	}
}