package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.util;

import java.util.EventObject;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class EventObject_2_6_MockUse {

	public EventObject obj = null;
	public EventObject_2_6_MockUse() {
		obj = new EventObject(
			new Object());
		callEventObjectMethods();
		callObjectMethods();
	}

	public void callEventObjectMethods() {
		obj.getSource();
		obj.toString();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}