package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.util;

import java.util.HashMap;
import java.util.IdentityHashMap;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class IdentityHashMap_2_6_MockUse {

	public IdentityHashMap obj = null;
	public IdentityHashMap_2_6_MockUse() {
		obj = new IdentityHashMap();
		obj = new IdentityHashMap(
			2);
		obj = new IdentityHashMap(
			new HashMap());
		callIdentityHashMapMethods();
		callObjectMethods();
		callAbstractMapMethods();
	}

	public void callIdentityHashMapMethods() {
		obj.containsKey(new Object());
		obj.containsValue(new Object());
		obj.equals(new Object());
		obj.isEmpty();
		obj.hashCode();
		obj.size();
		obj.clone();
		obj.get(new Object());
		obj.put(new Object(), new Object());
		obj.remove(new Object());
		obj.values();
		obj.entrySet();
		obj.keySet();
		obj.clear();
		obj.putAll(new HashMap());
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callAbstractMapMethods() {
		obj.containsKey(new Object());
		obj.containsValue(new Object());
		obj.equals(new Object());
		obj.isEmpty();
		obj.hashCode();
		obj.size();
		obj.get(new Object());
		obj.put(new Object(), new Object());
		obj.remove(new Object());
		obj.toString();
		obj.values();
		obj.entrySet();
		obj.keySet();
		obj.clear();
		obj.putAll(new HashMap());
	}
}
