package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.util;

import java.util.HashMap;
import java.util.LinkedHashMap;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class LinkedHashMap_2_6_MockUse {

	public LinkedHashMap obj = null;
	public LinkedHashMap_2_6_MockUse() {
		obj = new LinkedHashMap();
		obj = new LinkedHashMap(
			2);
		obj = new LinkedHashMap(
			2, (float) 0.2);
		obj = new LinkedHashMap(
			2, (float) 0.2, true);
		obj = new LinkedHashMap(
			new HashMap());
		callLinkedHashMapMethods();
		callObjectMethods();
		callAbstractMapMethods();
		callHashMapMethods();
	}

	public void callLinkedHashMapMethods() {
		obj.containsValue(new Object());
		obj.get(new Object());
		obj.clear();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callAbstractMapMethods() {
		obj.containsKey(new Object());
		obj.containsValue(new Object());
		obj.equals(new Object());
		obj.isEmpty();
		obj.hashCode();
		obj.size();
		obj.get(new Object());
		obj.put(new Object(), new Object());
		obj.remove(new Object());
		obj.toString();
		obj.values();
		obj.entrySet();
		obj.keySet();
		obj.clear();
		obj.putAll(new HashMap());
	}
	public void callHashMapMethods() {
		obj.containsKey(new Object());
		obj.containsValue(new Object());
		obj.isEmpty();
		obj.size();
		obj.clone();
		obj.get(new Object());
		obj.put(new Object(), new Object());
		obj.remove(new Object());
		obj.values();
		obj.entrySet();
		obj.keySet();
		obj.clear();
		obj.putAll(new HashMap());
	}
}
