package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.util;

import java.util.HashMap;
import java.util.Map;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Map_2_6_MockUse {

	public Map_2_6_MockUse(Map p) {
		p.containsKey(new Object());
		p.containsValue(new Object());
		p.equals(new Object());
		p.isEmpty();
		p.hashCode();
		p.size();
		p.get(new Object());
		p.put(new Object(), new Object());
		p.remove(new Object());
		p.values();
		p.entrySet();
		p.keySet();
		p.clear();
		p.putAll(new HashMap());
	}
}