package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.util;

import java.util.Comparator;
import java.util.Objects;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Objects_2_6_MockUse {

	public Objects_2_6_MockUse() {
		callObjectsMethods();
	}

	@SuppressWarnings({"static-access"})
	public void callObjectsMethods() {
		Objects.deepEquals(new Object(), new Object());
		Objects.equals(new Object(), new Object());
		Objects.compare(new Object(), new Object(), new Comparator<Object>() {

			@Override
			public int compare(Object o1, Object o2) {
				// TODO Auto-generated method stub
				return 0;
			}
		});
		Objects.hash(new Object[] {});
		Objects.hashCode(new Object());
		Objects.requireNonNull(new Object());
		Objects.requireNonNull(new Object(), "string");
		Objects.toString(new Object());
		Objects.toString(new Object(), "string");
	}
}