package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.util;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.PriorityQueue;
import java.util.TreeSet;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
@SuppressWarnings({"rawtypes", "unchecked"})
public class PriorityQueue_2_6_MockUse implements Comparator<Object>{

	
	public PriorityQueue obj = null;
	public PriorityQueue_2_6_MockUse() {
		obj = new PriorityQueue();
		obj = new PriorityQueue(
			2);
		obj = new PriorityQueue(
			2, this);
		obj = new PriorityQueue(
			new ArrayList<Object>());
		obj = new PriorityQueue(
			new PriorityQueue<Object>());
		obj = new PriorityQueue(
				new TreeSet<Object>());
		callPriorityQueueMethods();
		callObjectMethods();
		callAbstractCollectionMethods();
		callAbstractQueueMethods();
	}

	public void callPriorityQueueMethods() {
		
		
		obj.offer(new Object());
		new Object();
		obj.remove(new Object());
		obj.peek();
		obj.poll();
		obj.comparator();
	}
	public void callAbstractQueueMethods() {
		obj.add(new Object());
		obj.addAll(new PriorityQueue());
		obj.element();
		obj.remove();
		obj.clear();
		obj.offer(new Object());
		obj.poll();
		obj.peek();
		obj.add(new Object());
		obj.remove();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callAbstractCollectionMethods() {
		obj.toArray();
		obj.toArray(new Object[] {});
		obj.add(new Object());
		obj.addAll(new PriorityQueue());
		obj.contains(new Object());
		obj.containsAll(new PriorityQueue());
		obj.isEmpty();
		obj.remove(new Object());
		obj.removeAll(new PriorityQueue());
		obj.retainAll(new PriorityQueue());
		obj.size();
		obj.toString();
		obj.iterator();
		obj.clear();
	}

	@Override
	public int compare(Object o1, Object o2) {
		// TODO Auto-generated method stub
		return 0;
	}
}
