package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.util;

import java.util.RandomAccess;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class RandomAccess_2_6_MockUse {

	public RandomAccess_2_6_MockUse(RandomAccess p) {
	}
}

