package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.annotation;

import java.lang.annotation.RetentionPolicy;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class RetentionPolicy_2_6_MockUse {

	public RetentionPolicy obj = RetentionPolicy.CLASS;
	public java.lang.annotation.RetentionPolicy obj0 = RetentionPolicy.CLASS;
	public java.lang.annotation.RetentionPolicy obj1 = RetentionPolicy.RUNTIME;
	public java.lang.annotation.RetentionPolicy obj2 = RetentionPolicy.SOURCE;
	public RetentionPolicy_2_6_MockUse() {
		callRetentionPolicyMethods();
		callObjectMethods();
		callEnumMethods();
	}

	public void callRetentionPolicyMethods() {
		obj.values();
		obj.valueOf("CLASS");
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callEnumMethods() {
		obj.equals(new Object());
		obj.compareTo(RetentionPolicy.SOURCE);
		obj.hashCode();
		obj.ordinal();
		obj.getDeclaringClass();
		obj.valueOf(RetentionPolicy.class, "CLASS");
		obj.name();
		obj.toString();
	}
}