package org.adligo.tests4j_tests.models.shared.dependency_groups.jse;

import org.adligo.tests4j.models.shared.dependency_groups.jse.JSE_1_7_LangAnnot;
import org.adligo.tests4j.models.shared.trials.SourceFileScope;
import org.adligo.tests4j.models.shared.trials.Test;
import org.adligo.tests4j_tests.base_trials.I_CountType;
import org.adligo.tests4j_tests.base_trials.SourceFileCountingTrial;

@SourceFileScope (sourceClass=JSE_1_7_LangAnnot.class)
public class JSE_1_7_LangAnnotTrial extends SourceFileCountingTrial {

	@Test
	public void testConstants() {
		//autogenerated by org.adligo.tests4j_tests.models.shared.dependency_group.PackageClassNameWriter
		assertEquals("java.lang.annotation.Annotation",JSE_1_7_LangAnnot.ANNOTATION);
		assertEquals("java.lang.annotation.ElementType",JSE_1_7_LangAnnot.ELEMENT_TYPE);
		assertEquals("java.lang.annotation.RetentionPolicy",JSE_1_7_LangAnnot.RETENTION_POLICY);
		assertEquals("java.lang.annotation.AnnotationTypeMismatchException",JSE_1_7_LangAnnot.ANNOTATION_TYPE_MISMATCH_EXCEPTION);
		assertEquals("java.lang.annotation.IncompleteAnnotationException",JSE_1_7_LangAnnot.INCOMPLETE_ANNOTATION_EXCEPTION);
		assertEquals("java.lang.annotation.AnnotationFormatError",JSE_1_7_LangAnnot.ANNOTATION_FORMAT_ERROR);
		assertEquals("java.lang.annotation.Documented",JSE_1_7_LangAnnot.DOCUMENTED);
		assertEquals("java.lang.annotation.Inherited",JSE_1_7_LangAnnot.INHERITED);
		assertEquals("java.lang.annotation.Retention",JSE_1_7_LangAnnot.RETENTION);
		assertEquals("java.lang.annotation.Target",JSE_1_7_LangAnnot.TARGET);
	}
	@Override
	public int getTests(I_CountType type) {
		return super.getTests(type, 1);
	}

	@Override
	public int getAsserts(I_CountType type) {
		int thisAsserts = 10;
		//code coverage and circular dependencies +
		//custom afterTrialTests
		//+ see above
		int thisAfterAsserts = 2;
		if (type.isFromMetaWithCoverage()) {
			return super.getAsserts(type, thisAsserts + thisAfterAsserts);
		} else {
			return super.getAsserts(type, thisAsserts);
		}
	}

	@Override
	public int getUniqueAsserts(I_CountType type) {
		int thisUniqueAsserts = 10;
		//code coverage and circular dependencies +
		//custom afterTrialTests
		//+ see above
		int thisAfterUniqueAsserts = 2;
		if (type.isFromMetaWithCoverage()) {
			//code coverage and circular dependencies +
			//custom afterTrialTests
			return super.getUniqueAsserts(type, thisUniqueAsserts + thisAfterUniqueAsserts);
		} else {
			return super.getUniqueAsserts(type, thisUniqueAsserts);
		}
	}

}
