package org.adligo.tests4j_tests.models.dependency_groups.gwt.v2_6.lang;

import java.lang.NegativeArraySizeException;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class NegativeArraySizeException_2_6_MockUse {

	public NegativeArraySizeException obj = null;
	public NegativeArraySizeException_2_6_MockUse() {
		obj = new NegativeArraySizeException();
		obj = new NegativeArraySizeException(
			"string");
		callObjectMethods();
		callThrowableMethods();
	}

	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callObjectMethods() {
		obj.equals(null);
		obj.getClass();
		obj.hashCode();
		obj.toString();
	}
	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callThrowableMethods() {
		obj.getStackTrace();
		obj.getSuppressed();
		obj.getLocalizedMessage();
		obj.getMessage();
		obj.toString();
		obj.fillInStackTrace();
		obj.getCause();
		
		obj = new NegativeArraySizeException();
		obj.initCause(new Throwable());
		obj = new NegativeArraySizeException();
		obj.addSuppressed(new RuntimeException());
		obj.printStackTrace();
		obj.printStackTrace(System.out);
		obj.setStackTrace(new StackTraceElement[] {});
	}
}