package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.util;

import java.util.AbstractMap;
import java.util.HashMap;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class AbstractMap_2_6_MockUse {

	public AbstractMap obj = null;
	public AbstractMap_2_6_MockUse(AbstractMap am) {
		obj = am;
		callAbstractMapMethods();
		callObjectMethods();
	}

	public void callAbstractMapMethods() {
		obj.containsKey(new Object());
		obj.containsValue(new Object());
		obj.isEmpty();
		obj.size();
		obj.get(new Object());
		obj.put(new Object(), new Object());
		obj.remove(new Object());
		obj.values();
		obj.entrySet();
		obj.keySet();
		obj.clear();
		obj.putAll(new HashMap());
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}