package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.util;

import java.util.AbstractSet;
import java.util.ArrayList;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class AbstractSet_2_6_MockUse {

	public AbstractSet obj = null;
	public AbstractSet_2_6_MockUse(AbstractSet as) {
		obj = as;
		callAbstractSetMethods();
		callObjectMethods();
		callAbstractCollectionMethods();
	}

	public void callAbstractSetMethods() {
		obj.equals(new Object());
		obj.removeAll(new ArrayList());
		obj.hashCode();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callAbstractCollectionMethods() {
		obj.toArray();
		obj.toArray(new Object[] {});
		obj.add(new Object());
		obj.addAll(new ArrayList());
		obj.contains(new Object());
		obj.containsAll(new ArrayList());
		obj.isEmpty();
		obj.remove(new Object());
		obj.removeAll(new ArrayList());
		obj.retainAll(new ArrayList());
		obj.size();
		obj.toString();
		obj.iterator();
		obj.clear();
	}
}