package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.util;

import java.lang.annotation.ElementType;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.Map;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class EnumMap_2_6_MockUse {

	public EnumMap obj = new EnumMap(ElementType.class);
	public EnumMap_2_6_MockUse() {
		Map hm = new HashMap();
		hm.put(ElementType.ANNOTATION_TYPE, ElementType.ANNOTATION_TYPE);
		obj = new EnumMap(hm);
		obj = new EnumMap(
				ElementType.class);
		obj = new EnumMap(
				obj);
		
		callEnumMapMethods();
		callObjectMethods();
		callAbstractMapMethods();
	}

	public void callEnumMapMethods() {
		obj.clone();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callAbstractMapMethods() {
		obj.containsKey(new Object());
		obj.containsValue(new Object());
		obj.equals(new Object());
		obj.isEmpty();
		obj.hashCode();
		obj.size();
		obj.get(new Object());
		obj.put(ElementType.ANNOTATION_TYPE, ElementType.ANNOTATION_TYPE);
		
		obj.remove(ElementType.ANNOTATION_TYPE);
		obj.toString();
		obj.values();
		obj.entrySet();
		obj.keySet();
		obj.clear();
		obj.putAll(new EnumMap(ElementType.class));
	}
}
