package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.util;

import java.util.ListIterator;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class ListIterator_2_6_MockUse {

	public ListIterator_2_6_MockUse(ListIterator p) {
		p.hasNext();
		p.hasPrevious();
		p.nextIndex();
		p.previousIndex();
		p.next();
		p.previous();
		p.add(new Object());
		p.remove();
		p.set(new Object());
	}
}