package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.util;

import java.util.List;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class List_2_6_MockUse {

	public List_2_6_MockUse(List p) {
		p.toArray();
		p.toArray(null);
		p.add(new Object());
		p.addAll(2, null);
		p.addAll(null);
		p.contains(new Object());
		p.containsAll(null);
		p.equals(new Object());
		p.isEmpty();
		p.remove(new Object());
		p.removeAll(null);
		p.retainAll(null);
		p.hashCode();
		p.indexOf(new Object());
		p.lastIndexOf(new Object());
		p.size();
		p.get(2);
		p.remove(2);
		p.set(2, new Object());
		p.iterator();
		p.subList(2, 2);
		p.listIterator();
		p.listIterator(2);
		p.add(2, new Object());
		p.clear();
	}
}
