package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.util;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.TreeSet;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
@SuppressWarnings({"rawtypes","unchecked"})
public class TreeSet_2_6_MockUse {

	
	public TreeSet obj = null;
	public TreeSet_2_6_MockUse() {
		obj = new TreeSet();
		obj = new TreeSet(
			new HashSet());
		obj = new TreeSet(
			new TreeSet());
		obj = new TreeSet(
			new Comparator<Object>() {

				@Override
				public int compare(Object o1, Object o2) {
					// TODO Auto-generated method stub
					return 0;
				}
			});
		callTreeSetMethods();
		callObjectMethods();
		callAbstractCollectionMethods();
		callAbstractSetMethods();
	}

	public void callTreeSetMethods() {
		obj.size();
		obj.clone();
		obj.add(new Object());
		obj.first();
		obj.last();
		obj.comparator();
		obj.headSet(new Object());
		obj.subSet(new Object(), new Object());
		obj.tailSet(new Object());
	}

	public void callAbstractSetMethods() {
		obj.equals(new Object());
		obj.removeAll(new ArrayList());
		obj.hashCode();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callAbstractCollectionMethods() {
		obj.toArray();
		obj.toArray(new Object[] {});
		obj.add(new Object());
		obj.addAll(new ArrayList());
		obj.contains(new Object());
		obj.containsAll(new ArrayList());
		obj.isEmpty();
		obj.remove(new Object());
		obj.removeAll(new ArrayList());
		obj.retainAll(new ArrayList());
		obj.size();
		obj.toString();
		obj.iterator();
		obj.clear();
	}
}