package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.util;

import java.util.Date;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Date_2_6_MockUse {

	public Date obj = null;
	public Date_2_6_MockUse() {
		obj = new Date();
		obj = new Date(
			2, 2, 2);
		obj = new Date(
			2, 2, 2, 2, 2);
		obj = new Date(
			2, 2, 2, 2, 2, 2);
		obj = new Date(
			"12/31/1969");
		obj = new Date(
			3L);
		callDateMethods();
		callObjectMethods();
	}

	public void callDateMethods() {
		obj.after(new Date(1));
		obj.before(new Date(1));
		obj.equals(new Object());
		obj.compareTo(new Date(2));
		obj.getDate();
		obj.getDay();
		obj.getHours();
		obj.getMinutes();
		obj.getMonth();
		obj.getSeconds();
		obj.getTimezoneOffset();
		obj.getYear();
		obj.hashCode();
		obj.clone();
		obj.toGMTString();
		obj.toLocaleString();
		obj.toString();
		obj.UTC(2, 2, 2, 2, 2, 2);
		obj.getTime();
		obj.parse("12/31/1969");
		obj.setDate(2);
		obj.setHours(2);
		obj.setMinutes(2);
		obj.setMonth(2);
		obj.setSeconds(2);
		obj.setTime(3L);
		obj.setYear(2);
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}
