package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.util;

import java.lang.annotation.ElementType;
import java.util.EnumSet;
import java.util.HashSet;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class EnumSet_2_6_MockUse {

	public EnumSet<ElementType> obj = EnumSet.allOf(ElementType.class);
	public EnumSet_2_6_MockUse() {
		callEnumSetMethods();
		callObjectMethods();
		callAbstractCollectionMethods();
		callAbstractSetMethods();
	}

	public void callEnumSetMethods() {
		obj.clone();
		obj.allOf(ElementType.class);
		obj.clone();
		obj.complementOf(EnumSet.allOf(ElementType.class));
		obj.copyOf(EnumSet.allOf(ElementType.class));
		obj.copyOf(new HashSet(EnumSet.allOf(ElementType.class)));
		obj.noneOf(ElementType.class);
		obj.of(ElementType.ANNOTATION_TYPE);
		obj.of(ElementType.ANNOTATION_TYPE, new ElementType[] {});
	
		obj.range(ElementType.CONSTRUCTOR, ElementType.ANNOTATION_TYPE);
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callAbstractCollectionMethods() {
		obj.toArray();
		obj.toArray(new ElementType[0]);
		obj.add(ElementType.CONSTRUCTOR);
		obj.addAll(EnumSet.allOf(ElementType.class));
		obj.contains(new Object());
		obj.containsAll(EnumSet.allOf(ElementType.class));
		obj.isEmpty();
		obj.remove(new Object());
		obj.removeAll(EnumSet.allOf(ElementType.class));
		obj.retainAll(EnumSet.allOf(ElementType.class));
		obj.size();
		obj.toString();
		obj.iterator();
		obj.clear();
	}
	public void callAbstractSetMethods() {
		obj.equals(new Object());
		obj.removeAll(EnumSet.allOf(ElementType.class));
		obj.hashCode();
	}
}
