package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.util;

import java.util.Iterator;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Iterator_2_6_MockUse {

	public Iterator_2_6_MockUse(Iterator p) {
		p.hasNext();
		p.next();
		p.remove();
	}
}