package org.adligo.tests4j_v1_tests.models.shared.reference_groups.gwt.v2_6.util;

import java.util.SortedSet;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class SortedSet_2_6_MockUse {

	public SortedSet_2_6_MockUse(SortedSet p) {
		p.first();
		p.last();
		p.comparator();
		p.headSet(new Object());
		p.subSet(new Object(), new Object());
		p.tailSet(new Object());
	}
}