package org.adligo.tests4j_v1_tests.models.dependency_groups.gwt.v2_6.logging;

import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.LogRecord;
import java.util.logging.Logger;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Logger_2_6_MockUse {

	public Logger obj = Logger.getLogger("hmm");
	public Logger_2_6_MockUse() {
		callLoggerMethods();
		callObjectMethods();
	}

	public void callLoggerMethods() {
		obj.getHandlers();
		obj.getUseParentHandlers();
		obj.isLoggable(Level.INFO);
		obj.getName();
		obj.getLevel();
		obj.getLogger("string");
		obj.getParent();
		obj.addHandler(new Handler() {
			
			@Override
			public void publish(LogRecord record) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void flush() {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void close() throws SecurityException {
				// TODO Auto-generated method stub
				
			}
		});
		obj.config("string");
		obj.fine("string");
		obj.finer("string");
		obj.finest("string");
		obj.info("string");
		obj.log(Level.INFO, "string");
		obj.log(Level.INFO, "string", new Throwable());
		obj.log(new LogRecord(Level.INFO, "msg"));
		obj.removeHandler(null);
		obj.setLevel(Level.INFO);
		obj.setParent(Logger.getLogger("top"));
		obj.setUseParentHandlers(true);
		obj.severe("string");
		obj.warning("string");
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}
