package org.adligo.tests4j_v1_tests.gwt_refs.v2_6.logging;

import java.util.logging.Level;
import java.util.logging.LogRecord;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class LogRecord_2_6_MockUse {

	public LogRecord obj = null;
	public LogRecord_2_6_MockUse() {
		obj = new LogRecord(
			Level.ALL, "string");
		callLogRecordMethods();
		callObjectMethods();
	}

	public void callLogRecordMethods() {
		obj.getLoggerName();
		obj.getMessage();
		obj.getThrown();
		obj.getLevel();
		obj.getMillis();
		obj.setLevel(Level.INFO);
		obj.setLoggerName("string");
		obj.setMessage("string");
		obj.setMillis(3L);
		obj.setThrown(new Throwable());
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
}
