package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.annotation;


import java.lang.annotation.AnnotationTypeMismatchException;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class AnnotationTypeMismatchException_2_6_MockUse {

	public AnnotationTypeMismatchException obj = null;
	public AnnotationTypeMismatchException_2_6_MockUse() {
		obj = new AnnotationTypeMismatchException(
			null, "string");
		callAnnotationTypeMismatchExceptionMethods();
		callObjectMethods();
		callThrowableMethods();
	}

	public void callAnnotationTypeMismatchExceptionMethods() {
		obj.foundType();
		obj.element();
	}
	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callObjectMethods() {
		obj.equals(null);
		obj.getClass();
		obj.hashCode();
		obj.toString();
	}
	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callThrowableMethods() {
		obj.getStackTrace();
		obj.getSuppressed();
		obj.getLocalizedMessage();
		obj.getMessage();
		obj.toString();
		obj.fillInStackTrace();
		obj.getCause();
		
		obj = new AnnotationTypeMismatchException(null, "string");
		obj.initCause(new Throwable());
		obj = new AnnotationTypeMismatchException(null, "string");
		obj.addSuppressed(new RuntimeException());
		obj.printStackTrace();
		obj.printStackTrace(System.out);
		obj.setStackTrace(new StackTraceElement[] {});
	}
}