package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.annotation;

import java.lang.annotation.ElementType;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class ElementType_2_6_MockUse {

	public ElementType obj = ElementType.TYPE;
	public java.lang.annotation.ElementType obj0 = ElementType.ANNOTATION_TYPE;
	public java.lang.annotation.ElementType obj1 = ElementType.CONSTRUCTOR;
	public java.lang.annotation.ElementType obj2 = ElementType.FIELD;
	public java.lang.annotation.ElementType obj3 = ElementType.LOCAL_VARIABLE;
	public java.lang.annotation.ElementType obj4 = ElementType.METHOD;
	public java.lang.annotation.ElementType obj5 = ElementType.PACKAGE;
	public java.lang.annotation.ElementType obj6 = ElementType.PARAMETER;
	public java.lang.annotation.ElementType obj7 = ElementType.TYPE;
	public ElementType_2_6_MockUse() {
		callElementTypeMethods();
		callObjectMethods();
		callEnumMethods();
	}

	public void callElementTypeMethods() {
		obj.values();
		obj.valueOf("TYPE");
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callEnumMethods() {
		obj.compareTo(ElementType.TYPE);
		obj.ordinal();
		obj.getDeclaringClass();
		obj.valueOf(ElementType.class, "TYPE");
		obj.name();
	}
}