package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.annotation;

import java.lang.annotation.Target;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Target_2_6_MockUse {

	public Target_2_6_MockUse(Target p) {
		p.value();
	}
}