package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.lang;

import java.lang.AutoCloseable;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class AutoCloseable_2_6_MockUse {

	public AutoCloseable_2_6_MockUse(AutoCloseable p) throws Exception {
		p.close();
	}
}