package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.lang;

import java.lang.Byte;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Byte_2_6_MockUse {

	public Byte obj = null;
	public byte obj0 = Byte.MAX_VALUE;
	public byte obj1 = Byte.MIN_VALUE;
	public int obj2 = Byte.SIZE;
	
	public java.lang.Class obj3 = Byte.TYPE;
	
	public Byte_2_6_MockUse() {
		obj = new Byte((byte) 0);
		obj = new Byte(
			"0");
		callByteMethods();
		callObjectMethods();
		callNumberMethods();
	}

	public void callByteMethods() {
		obj.equals(new Object());
		obj.byteValue();
		obj.parseByte("0");
		obj.parseByte("0", 2);
		obj.doubleValue();
		obj.floatValue();
		obj.compare((byte) 0,(byte)  0);
		obj.compareTo(new Byte((byte) 0));
		obj.hashCode();
		obj.intValue();
		obj.decode("0");
		obj.valueOf((byte) 0);
		obj.valueOf("0");
		obj.valueOf("0", 2);
		obj.toString();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callNumberMethods() {
		obj.byteValue();
		obj.doubleValue();
		obj.floatValue();
		obj.intValue();
		obj.longValue();
		obj.shortValue();
	}
}