package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.lang;

import java.lang.Comparable;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Comparable_2_6_MockUse {

	public Comparable_2_6_MockUse(Comparable<Object> p) {
		p.compareTo(new Object());
	}
}