package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.lang;


/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Deprecated_2_6_MockUse {

	@Deprecated
	public Deprecated_2_6_MockUse() {
	}
}