package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.lang;

import java.lang.Float;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Float_2_6_MockUse {

	public Float obj = null;
	public int obj0 = Float.MAX_EXPONENT;
	public float obj1 = Float.MAX_VALUE;
	public int obj2 = Float.MIN_EXPONENT;
	public float obj3 = Float.MIN_NORMAL;
	public float obj4 = Float.MIN_VALUE;
	public float obj5 = Float.NEGATIVE_INFINITY;
	public float obj6 = Float.NaN;
	public float obj7 = Float.POSITIVE_INFINITY;
	public int obj8 = Float.SIZE;
	public java.lang.Class obj9 = Float.TYPE;
	public Float_2_6_MockUse() {
		obj = new Float(
			0.1);
		obj = new Float(
			(float) 0.2);
		obj = new Float(
			"20.0");
		callFloatMethods();
		callObjectMethods();
		callNumberMethods();
	}

	public void callFloatMethods() {
		obj.equals(new Object());
		obj.isNaN();
		obj.isNaN((float) 0.2);
		obj.byteValue();
		obj.doubleValue();
		obj.floatValue();
		obj.intBitsToFloat(2);
		obj.parseFloat("0.2");
		obj.compare((float) 0.2, (float) 0.2);
		obj.compareTo(new Float(2.0));
		obj.floatToIntBits((float) 0.2);
		obj.intValue();
		obj.valueOf((float) 0.2);
		obj.valueOf("0.2");
		obj.toString();
		obj.toString((float) 0.2);
		obj.longValue();
		obj.shortValue();
	}
	public void callObjectMethods() {
		obj.equals(new Object());
		obj.hashCode();
		obj.getClass();
		obj.toString();
	}
	public void callNumberMethods() {
		obj.byteValue();
		obj.doubleValue();
		obj.floatValue();
		obj.intValue();
		obj.longValue();
		obj.shortValue();
	}
}