package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.lang;

import java.lang.IllegalArgumentException;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class IllegalArgumentException_2_6_MockUse {

	public IllegalArgumentException obj = null;
	public IllegalArgumentException_2_6_MockUse() {
		obj = new IllegalArgumentException();
		obj = new IllegalArgumentException(
			"string");
		obj = new IllegalArgumentException(
			"string", new Throwable());
		obj = new IllegalArgumentException(
			new Throwable());
		callObjectMethods();
		callThrowableMethods();
	}


	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callObjectMethods() {
		obj.equals(null);
		obj.getClass();
		obj.hashCode();
		obj.toString();
	}
	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callThrowableMethods() {
		obj.getStackTrace();
		obj.getSuppressed();
		obj.getLocalizedMessage();
		obj.getMessage();
		obj.toString();
		obj.fillInStackTrace();
		obj.getCause();
		
		obj = new IllegalArgumentException();
		obj.initCause(new Throwable());
		obj = new IllegalArgumentException();
		obj.addSuppressed(new RuntimeException());
		obj.printStackTrace();
		obj.printStackTrace(System.out);
		obj.setStackTrace(new StackTraceElement[] {});
	}
}