package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.lang;

import java.lang.AutoCloseable;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Runnable_2_6_MockUse {

	public Runnable_2_6_MockUse(Runnable p) throws Exception {
		p.run();
	}
}