package org.adligo.tests4j_v1_tests.models.shared.dependency_groups.gwt.v2_6.lang;

import java.lang.StackTraceElement;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class StackTraceElement_2_6_MockUse {

	public StackTraceElement obj = null;
	public StackTraceElement_2_6_MockUse() {
		obj = new StackTraceElement(
			"string", "string", "string", 2);
		callObjectMethods();
		callStackTraceElementMethods();
		
	}

	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callObjectMethods() {
		obj.equals(null);
		obj.getClass();
		obj.hashCode();
		obj.toString();
	}
	
	public void callStackTraceElementMethods() {
		obj.getLineNumber();
		obj.getClassName();
		obj.getFileName();
		obj.getMethodName();
		obj.toString();
	}
}