package org.adligo.tests4j_tests.models.shared.dependency_groups.gwt.v2_6.lang;

import java.lang.Exception;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Exception_2_6_MockUse {

	public Exception obj = null;
	public Exception_2_6_MockUse() {
		obj = new Exception();
		obj = new Exception(
			"string");
		obj = new Exception(
			"string", new Throwable());
		obj = new Exception(
			new Throwable());
		callObjectMethods();
		callThrowableMethods();
	}

	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callObjectMethods() {
		obj.equals(null);
		obj.getClass();
		obj.hashCode();
		obj.toString();
	}
	/**
	 * this needs to be generated each
	 * time so the instance getting methods called
	 * on it is the correct type.
	 */
	public void callThrowableMethods() {
		obj = new Exception();
		obj.initCause(new Throwable("hmm"));
		obj.addSuppressed(new Throwable());
		
		obj.getStackTrace();
		obj.getSuppressed();
		obj.getLocalizedMessage();
		obj.getMessage();
		obj.toString();
		obj.fillInStackTrace();
		obj.getCause();
		
		obj.printStackTrace();
		obj.printStackTrace(System.out);
		obj.setStackTrace(new StackTraceElement[] {});
	}
}