package org.adligo.tests4j_tests.models.shared.dependency_groups.gwt.v2_6.lang;

/** autogenerated by org.adligo.tests4j.gen.dependency_groups.ClassUseGen*/
public class Object_2_6_MockUse {

	public Object obj = null;
	public Object_2_6_MockUse() {
		obj = new Object();
		useObjectMethods(obj);
	}
	
	public static void useObjectMethods(Object obj) {
		obj.equals(null);
		obj.getClass();
		obj.hashCode();
		obj.toString();
	}
}